---
- hosts: all
  remote_user: root
  become_method: yes
  vars: 
    http_port: 8080
    https_port: 8443
  tasks:
    - name: Make sure that we can connect to the machine
      ping:
    -name: create opt dir
     command: mkdir -p tomcat

    - name: Download Tomcat
      get_url: 
        url: http://mirrors.estointernet.in/apache/tomcat/tomcat-9/v9.0.16/bin/apache-tomcat-9.0.16.tar.gz
        dest: tomcat/

    - name: copy Tomcat
      copy: 
        src: ./apache-tomcat-9.0.16.tar.gz 
        dest: tomcat//apache-tomcat-9.0.16.tar.gz

    - name: Extract Tomcat archive
      command: tar zxvf /opt/apache-tomcat-9.0.16.tar.gz -C tomcat/ creates=tomcat/apache-tomcat-9.0.16

    - name: Configure Tomcat users
      template: src=tomcat-users.xml dest=/opt/apache-tomcat-9.0.16/conf/

    - name: Start Tomcat
      command: sudo /opt/apache-tomcat-9.0.16/bin/startup.sh
      become: true
      become_user: root

    - name: print something
      debug: "ashok"
